version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout

      - run:
          name: Install Rust
          command: |
            $installer = $env:TEMP + "\rustup-init.exe"
            Invoke-WebRequest https://win.rustup.rs/ -OutFile $installer
            Start-Process -FilePath $installer -Args "/y" -Wait
            $env:Path += ";$env:USERPROFILE\.cargo\bin"
            rustup default stable
            rustup component add rustfmt clippy

      - run:
          name: Add wasm32-wasi target
          command: rustup target add wasm32-wasi

      - run:
          name: Install Visual Studio components
          command: choco install visualstudio2019buildtools visualstudio2019-workload-vctools

      - run:
          name: Download cache
          command: |
            $cacheKey = (Get-FileHash -Path Cargo.lock -Algorithm SHA256).Hash
            $cacheFileName = "cache-$cacheKey.tar.gz"
            $downloadUrl = "https://storage.erensprojects.web.tr/api/download/$cacheFileName"
            
            try {
              Invoke-WebRequest -Uri $downloadUrl -OutFile cache.tar.gz
              if (Test-Path cache.tar.gz) {
                tar -xzf cache.tar.gz -C C:\Users\circleci\
                Write-Host "Cache downloaded and extracted successfully."
              }
            } catch {
              Write-Host "Cache file not found or error downloading. Proceeding without cache."
            }

      - run:
          name: Build Zed (Release)
          command: cargo build --release

      - run:
          name: Save cache
          command: |
            $cacheKey = (Get-FileHash -Path Cargo.lock -Algorithm SHA256).Hash
            tar -czf cache.tar.gz -C C:\Users\circleci\ .cargo\registry .cargo\git target
            curl.exe -X POST https://storage.erensprojects.web.tr/api/upload `
              -H "Content-Type: multipart/form-data" `
              -F "file=@cache.tar.gz" `
              -F "filename=cache-$cacheKey.tar.gz"

      - run:
          name: Upload artifact
          command: |
            curl.exe -X POST https://storage.erensprojects.web.tr/api/upload `
              -H "Content-Type: multipart/form-data" `
              -F "file=@target\release\zed.exe"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main