name: Build Zed for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Enable long paths in Git
      run: |
        git config --system core.longpaths true
    
    - name: Configure Windows long paths
      shell: powershell
      run: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
        -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
    
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Add wasm32-wasi target
      run: rustup target add wasm32-wasi
    
    - name: Install Visual Studio components
      uses: microsoft/setup-msbuild@v2
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build Zed (Release)
      shell: pwsh
      run: |
        $env:CARGO_HOME = "D:\cargo"
        cargo build --release
    
    - name: Upload Zed artifact
      uses: actions/upload-artifact@v4
      with:
        name: zed-windows
        path: target/release/zed.exe
