name: Build Zed for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Add wasm32-wasi target
      run: rustup target add wasm32-wasi
    
    - name: Install Visual Studio components
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build Zed (Release)
      run: cargo build --release
    
    - name: Run tests
      run: cargo test --workspace
    
    - name: Upload Zed artifact
      uses: actions/upload-artifact@v3
      with:
        name: zed-windows
        path: target/release/zed.exe
